name: Deploy to Deno Deploy
description: Deploy your applications to Deno Deploy, right from GitHub Actions
author: Deno Land Inc

branding:
  color: gray-dark
  icon: globe

inputs:
  deno-config:
    description: The path to a deno config file that will populate other inputs (optional, deno.json and deno.jsonc are auto-discovered)
    required: false
  project:
    description: The name or ID of the project to deploy (required)
    required: false
  entrypoint:
    description: The path or URL to the entrypoint file (required)
    required: false
  import-map:
    description: The path or URL to an import map file
    required: false
  include:
    description: Only upload files that match this pattern (multiline and/or comma-separated)
    required: false
  exclude:
    description: Exclude files that match this pattern (multiline and/or comma-separated)
    required: false
  root:
    description: The path to the directory containing the code and assets to upload
    required: false
  import-map-autogen-temp:
    description: The path to store the auto-generated import map if deno config file is present (relative to root)
    required: false
    default: ".importMap.generated.json"

outputs:
  deployment-id:
    description: The ID of the created deployment
  url:
    description: The URL where the deployment is reachable

runs:
  using: node20
  main: action/index.js
